from __future__ import annotations

from langchain_core.documents import Document
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

from policypilot.vectorstore.chroma_store import ChromaStore

from .rag_models import RAGResponse, RAGSource
from .rag_prompt import create_rag_prompt


class RAGService:
    """
    Connect ChromaDB retrieval with the PolicyPilot language model.

    The service performs the following steps:

    1. Receive and validate a user question.
    2. Retrieve relevant policy chunks from ChromaDB.
    3. Convert the retrieved chunks into readable context.
    4. Add the context and question to the RAG prompt.
    5. Send the prompt to the language model.
    6. Convert the model response into a string.
    7. Return a validated Pydantic response.
    """

    def __init__(
        self,
        vector_store: ChromaStore,
        llm: BaseChatModel,
        number_of_results: int = 3,
        prompt: ChatPromptTemplate | None = None,
    ) -> None:
        """
        Initialize the PolicyPilot RAG service.

        Args:
            vector_store:
                Existing PolicyPilot ChromaStore object.

            llm:
                Configured LangChain chat model, such as ChatOllama.

            number_of_results:
                Maximum number of policy chunks to retrieve
                for each question.

            prompt:
                Optional custom prompt template. If no prompt is
                provided, the default PolicyPilot RAG prompt is used.

        Raises:
            TypeError:
                If an argument has an incorrect type.

            ValueError:
                If number_of_results is less than one.
        """

        if not isinstance(vector_store, ChromaStore):
            raise TypeError(
                "vector_store must be an instance of ChromaStore, "
                f"but received {type(vector_store).__name__}."
            )

        if not isinstance(llm, BaseChatModel):
            raise TypeError(
                "llm must be an instance of BaseChatModel, "
                f"but received {type(llm).__name__}."
            )

        if not isinstance(number_of_results, int):
            raise TypeError(
                "number_of_results must be an integer, "
                f"but received {type(number_of_results).__name__}."
            )

        if number_of_results < 1:
            raise ValueError(
                "number_of_results must be greater than zero."
            )

        if prompt is not None and not isinstance(
            prompt,
            ChatPromptTemplate,
        ):
            raise TypeError(
                "prompt must be a ChatPromptTemplate or None, "
                f"but received {type(prompt).__name__}."
            )

        self._vector_store = vector_store
        self._llm = llm
        self._number_of_results = number_of_results

        self._prompt = (
            prompt if prompt is not None else create_rag_prompt()
        )

        self._rag_chain = (
            self._prompt
            | self._llm
            | StrOutputParser()
        )

    def answer_question(self, question: str) -> RAGResponse:
        """
        Answer a question using retrieved policy documents.

        Args:
            question:
                User question about the indexed policy documents.

        Returns:
            A validated RAGResponse containing:

            - The original question.
            - The answer generated by the language model.
            - The policy chunks used as context.

        Raises:
            TypeError:
                If question is not a string or the RAG chain
                returns an unexpected result type.

            ValueError:
                If question is empty or the language model
                returns an empty answer.
        """

        normalized_question = self._validate_question(question)

        search_results = (
            self._vector_store.similarity_search_with_score(
                query=normalized_question,
                number_of_results=self._number_of_results,
            )
        )

        if not search_results:
            return RAGResponse(
                question=normalized_question,
                answer=(
                    "I could not find this information in the "
                    "provided policy documents."
                ),
                sources=(),
            )

        sources = self._create_sources(search_results)
        context = self._format_context(sources)

        answer = self._rag_chain.invoke(
            {
                "context": context,
                "question": normalized_question,
            }
        )

        if not isinstance(answer, str):
            raise TypeError(
                "Expected the RAG chain to return a string, "
                f"but received {type(answer).__name__}."
            )

        normalized_answer = answer.strip()

        if not normalized_answer:
            raise ValueError(
                "The language model returned an empty answer."
            )

        return RAGResponse(
            question=normalized_question,
            answer=normalized_answer,
            sources=sources,
        )

    @staticmethod
    def _validate_question(question: str) -> str:
        """
        Validate and clean the user question.

        Args:
            question:
                Question that should be validated.

        Returns:
            The cleaned question.

        Raises:
            TypeError:
                If question is not a string.

            ValueError:
                If question is empty after removing whitespace.
        """

        if not isinstance(question, str):
            raise TypeError(
                "question must be a string, "
                f"but received {type(question).__name__}."
            )

        normalized_question = question.strip()

        if not normalized_question:
            raise ValueError("question must not be empty.")

        return normalized_question

    @staticmethod
    def _create_sources(
        search_results: list[tuple[Document, float]],
    ) -> tuple[RAGSource, ...]:
        """
        Convert ChromaDB results into validated RAGSource models.

        Args:
            search_results:
                List containing retrieved documents and their
                similarity scores.

        Returns:
            An immutable tuple of validated RAGSource objects.
        """

        sources: list[RAGSource] = []

        for document, score in search_results:
            metadata = document.metadata

            chunk_id = str(
                metadata.get(
                    "chunk_id",
                    "unknown",
                )
            )

            source = str(
                metadata.get(
                    "source",
                    metadata.get(
                        "file_name",
                        metadata.get(
                            "document_name",
                            "unknown",
                        ),
                    ),
                )
            )

            content = document.page_content.strip()

            rag_source = RAGSource(
                chunk_id=chunk_id,
                source=source,
                score=float(score),
                content=content,
            )

            sources.append(rag_source)

        return tuple(sources)

    @staticmethod
    def _format_context(
        sources: tuple[RAGSource, ...],
    ) -> str:
        """
        Convert retrieved policy chunks into readable LLM context.

        Args:
            sources:
                Validated policy chunks retrieved from ChromaDB.

        Returns:
            Formatted context containing the chunk identifier,
            source document, and policy text.
        """

        context_parts: list[str] = []

        for position, source in enumerate(
            sources,
            start=1,
        ):
            context_part = (
                f"[Policy chunk {position}]\n"
                f"Chunk ID: {source.chunk_id}\n"
                f"Source: {source.source}\n"
                f"Content:\n{source.content}"
            )

            context_parts.append(context_part)

        return "\n\n".join(context_parts)