from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class RAGSource(BaseModel):
    """
    Represent one policy chunk retrieved from ChromaDB.

    Attributes:
        chunk_id:
            Stable identifier of the retrieved policy chunk.

        source:
            Name or path of the original policy document.

        score:
            Similarity score returned by ChromaDB.

        content:
            Text content of the retrieved policy chunk.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        str_strip_whitespace=True,
    )

    """
        frozen=True: prevents changing fields after creation.
        extra="forbid": rejects unknown fields.
        str_strip_whitespace=True: removes leading and trailing spaces from string fields.
    """
    


    chunk_id: str = Field(
        min_length=1,
        description="Stable identifier of the retrieved policy chunk.",
    )

    source: str = Field(
        min_length=1,
        description="Name or path of the original policy document.",
    )

    score: float = Field(
        description="Similarity score returned by ChromaDB.",
    )

    content: str = Field(
        min_length=1,
        description="Text content of the retrieved policy chunk.",
    )


class RAGResponse(BaseModel):
    """
    Represent the final result returned by the RAG service.

    Attributes:
        question:
            Original question provided by the user.

        answer:
            Answer generated by the language model.

        sources:
            Policy chunks retrieved from ChromaDB and used
            as context for the language model.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        str_strip_whitespace=True,
    )

    question: str = Field(
        min_length=1,
        description="Original policy question provided by the user.",
    )

    answer: str = Field(
        min_length=1,
        description="Answer generated from the retrieved policy context.",
    )

    sources: tuple[RAGSource, ...] = Field(
        default_factory=tuple,
        description="Policy chunks used to generate the answer.",
    )