from __future__ import annotations

from dataclasses import dataclass

from langchain_core.documents import Document
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.prompts import ChatPromptTemplate

from policypilot.vectorstore.chroma_store import ChromaStore

from .rag_prompt import create_rag_prompt


@dataclass(frozen=True)
class RAGSource:
    """
    Represent one policy chunk retrieved from ChromaDB.

    Attributes:
        chunk_id:
            Stable identifier of the retrieved chunk.

        source:
            Name or path of the original policy document.

        score:
            Similarity score returned by ChromaDB.

        content:
            Text stored inside the retrieved chunk.
    """

    chunk_id: str
    source: str
    score: float
    content: str


@dataclass(frozen=True)
class RAGResponse:
    """
    Represent the final result of a PolicyPilot question.

    Attributes:
        question:
            The original user question.

        answer:
            Answer generated by the language model.

        sources:
            Policy chunks used to produce the answer.
    """

    question: str
    answer: str
    sources: tuple[RAGSource, ...]


class RAGService:
    """
    Connect ChromaDB retrieval with the PolicyPilot language model.

    The service performs these steps:

    1. Receive a user question.
    2. Retrieve relevant policy chunks from ChromaDB.
    3. Format the retrieved chunks as policy context.
    4. Add the question and context to the RAG prompt.
    5. Send the messages to the language model.
    6. Return the answer and retrieved sources.
    """

    def __init__(
        self,
        vector_store: ChromaStore,
        llm: BaseChatModel,
        number_of_results: int = 3,
        prompt: ChatPromptTemplate | None = None,
    ) -> None:
        """
        Initialize the PolicyPilot RAG service.

        Args:
            vector_store:
                Existing PolicyPilot ChromaStore object.

            llm:
                Configured LangChain chat model.

            number_of_results:
                Maximum number of policy chunks to retrieve.

            prompt:
                Optional custom prompt template. When it is not
                provided, the default PolicyPilot prompt is used.

        Raises:
            TypeError:
                If an argument has an incorrect type.

            ValueError:
                If number_of_results is less than one.
        """

        if not isinstance(vector_store, ChromaStore):
            raise TypeError(
                "vector_store must be an instance of ChromaStore, "
                f"but received {type(vector_store).__name__}."
            )

        if not isinstance(llm, BaseChatModel):
            raise TypeError(
                "llm must be an instance of BaseChatModel, "
                f"but received {type(llm).__name__}."
            )

        if not isinstance(number_of_results, int):
            raise TypeError(
                "number_of_results must be an integer, "
                f"but received {type(number_of_results).__name__}."
            )

        if number_of_results < 1:
            raise ValueError(
                "number_of_results must be greater than zero."
            )

        if prompt is not None and not isinstance(
            prompt,
            ChatPromptTemplate,
        ):
            raise TypeError(
                "prompt must be a ChatPromptTemplate or None, "
                f"but received {type(prompt).__name__}."
            )

        self._vector_store = vector_store
        self._llm = llm
        self._number_of_results = number_of_results
        self._prompt = (
            prompt if prompt is not None else create_rag_prompt()
        )

    def answer_question(self, question: str) -> RAGResponse:
        """
        Answer a question using retrieved policy chunks.

        Args:
            question:
                User question about the policy documents.

        Returns:
            A RAGResponse containing the generated answer
            and the retrieved policy sources.

        Raises:
            TypeError:
                If question is not a string.

            ValueError:
                If question is empty or the model returns
                an empty answer.
        """

        normalized_question = self._validate_question(question)

        search_results = (
            self._vector_store.similarity_search_with_score(
                query=normalized_question,
                number_of_results=self._number_of_results,
            )
        )

        if not search_results:
            return RAGResponse(
                question=normalized_question,
                answer=(
                    "I could not find this information in the "
                    "provided policy documents."
                ),
                sources=(),
            )

        sources = self._create_sources(search_results)
        context = self._format_context(sources)

        messages = self._prompt.format_messages(
            context=context,
            question=normalized_question,
        )

        response = self._llm.invoke(messages)
        answer = self._extract_answer(response)

        return RAGResponse(
            question=normalized_question,
            answer=answer,
            sources=sources,
        )

    @staticmethod
    def _validate_question(question: str) -> str:
        """
        Validate and clean the user question.

        Args:
            question:
                Question that should be validated.

        Returns:
            The cleaned question.

        Raises:
            TypeError:
                If question is not a string.

            ValueError:
                If question is empty.
        """

        if not isinstance(question, str):
            raise TypeError(
                "question must be a string, "
                f"but received {type(question).__name__}."
            )

        normalized_question = question.strip()

        if not normalized_question:
            raise ValueError("question must not be empty.")

        return normalized_question

    @staticmethod
    def _create_sources(
        search_results: list[tuple[Document, float]],
    ) -> tuple[RAGSource, ...]:
        """
        Convert ChromaDB search results into RAGSource objects.

        Args:
            search_results:
                Documents and scores returned by ChromaDB.

        Returns:
            An immutable tuple containing the retrieved sources.
        """

        sources: list[RAGSource] = []

        for document, score in search_results:
            metadata = document.metadata

            chunk_id = str(
                metadata.get("chunk_id", "unknown")
            )

            source = str(
                metadata.get(
                    "source",
                    metadata.get(
                        "file_name",
                        metadata.get(
                            "document_name",
                            "unknown",
                        ),
                    ),
                )
            )

            sources.append(
                RAGSource(
                    chunk_id=chunk_id,
                    source=source,
                    score=float(score),
                    content=document.page_content.strip(),
                )
            )

        return tuple(sources)

    @staticmethod
    def _format_context(
        sources: tuple[RAGSource, ...],
    ) -> str:
        """
        Convert retrieved policy chunks into readable context.

        Args:
            sources:
                Policy chunks retrieved from ChromaDB.

        Returns:
            Formatted text that can be passed to the LLM.
        """

        context_parts: list[str] = []

        for position, source in enumerate(sources, start=1):
            context_parts.append(
                f"[Policy chunk {position}]\n"
                f"Chunk ID: {source.chunk_id}\n"
                f"Source: {source.source}\n"
                f"Content:\n{source.content}"
            )

        return "\n\n".join(context_parts)

    @staticmethod
    def _extract_answer(response: BaseMessage) -> str:
        """
        Extract and validate the answer returned by the LLM.

        Args:
            response:
                Message returned by the LangChain chat model.

        Returns:
            Clean answer text.

        Raises:
            TypeError:
                If the response is not an AIMessage or its
                content is not a string.

            ValueError:
                If the returned answer is empty.
        """

        if not isinstance(response, AIMessage):
            raise TypeError(
                "Expected an AIMessage from the LLM, "
                f"but received {type(response).__name__}."
            )

        if not isinstance(response.content, str):
            raise TypeError(
                "Expected the LLM response content to be a string, "
                f"but received {type(response.content).__name__}."
            )

        answer = response.content.strip()

        if not answer:
            raise ValueError(
                "The language model returned an empty answer."
            )

        return answer