from __future__ import annotations

import torch

from policypilot.embeddings.embed_documents import (
    EXPECTED_EMBEDDING_DIMENSION,
    DocumentEmbeddingResult,
    embed_documents_from_jsonl,
)
from policypilot.embeddings.embedding_config import (
    EmbeddingConfig,
)
from policypilot.ingestion.config import (
    DEFAULT_CHUNKS_OUTPUT_FILE,
)


def display_embedding_result(
    result: DocumentEmbeddingResult,
) -> None:
    """
    Display a summary of the generated document embeddings.

    Args:
        result:
            Documents and embeddings generated by the embedding pipeline.
    """

    print("\nEmbedding generation completed successfully.")
    print(f"Documents loaded: {result.document_count}")
    print(f"Embeddings generated: {result.embedding_count}")
    print(
        f"Embedding dimension: {result.embedding_dimension}"
    )

    first_document = result.documents[0]
    first_embedding = result.embeddings[0]

    print("\n" + "=" * 60)
    print("First document")
    print("=" * 60)

    print(
        "Chunk ID: "
        f"{first_document.metadata.get('chunk_id', 'not available')}"
    )

    print("\nMetadata:")
    print(first_document.metadata)

    print("\nContent preview:")
    print(first_document.page_content[:300])

    print("\nFirst five embedding values:")
    print(first_embedding[:5])


def main() -> None:
    """
    Load PolicyPilot JSONL chunks and generate embeddings.
    """

    config = EmbeddingConfig(
        device="auto",
        batch_size=32,
        normalize_embeddings=True,
        show_progress_bar=True,
    )

    selected_device = config.resolve_device()

    print("=" * 60)
    print("PolicyPilot Document Embedding Pipeline")
    print("=" * 60)

    print(f"Input JSONL file: {DEFAULT_CHUNKS_OUTPUT_FILE}")
    print(f"Embedding model: {config.model_name}")
    print(f"Selected device: {selected_device}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"Batch size: {config.batch_size}")
    print(
        "Expected embedding dimension: "
        f"{EXPECTED_EMBEDDING_DIMENSION}"
    )

    print("\nLoading documents from JSONL...")
    print("Generating embeddings...")

    try:
        result = embed_documents_from_jsonl(
            jsonl_file=DEFAULT_CHUNKS_OUTPUT_FILE,
            config=config,
            expected_dimension=EXPECTED_EMBEDDING_DIMENSION,
        )
    except (
        FileNotFoundError,
        TypeError,
        ValueError,
        RuntimeError,
    ) as error:
        print("\nEmbedding pipeline failed.")
        print(f"Reason: {error}")
        raise SystemExit(1) from error

    display_embedding_result(result)

    print(
        "\nThe embeddings currently exist in memory."
    )
    print(
        "The next step will store these documents and embeddings "
        "in Chroma."
    )


if __name__ == "__main__":
    main()