from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class LLMConfig(BaseModel):
    """
    Configuration for the PolicyPilot language model.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        str_strip_whitespace=True,
    )

    model_name: str = Field(
        default="llama3.2:1b",
        min_length=1,
        description="Name of the Ollama model.",
    )

    base_url: str = Field(
        default="http://localhost:11434",
        min_length=1,
        description="Base URL of the Ollama server.",
    )

    temperature: float = Field(
        default=0.0,
        ge=0.0,
        le=2.0,
        description="Controls randomness in model responses.",
    )

    max_output_tokens: int = Field(
        default=512,
        gt=0,
        description="Maximum number of tokens generated by the model.",
    )

    validate_model_on_init: bool = Field(
        default=True,
        description="Validate that the Ollama model exists during initialization.",
    )